[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
rand = "0.8.4"
toml = "0.8.10"
actix-files = "0.6.0"
actix-cors = "0.7.0"
tokio-stream = "0.1.7"
async-trait = "0.1"
reqwest = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive","serde_derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
redis = {version = "0.25", features = ["aio","tokio-comp","async-std-comp"]}